### PR TITLE
comments on srihari's work

### PR DESCRIPTION
**Pull request by aboehmke**

### CODE REVIEW

**Comment by sriharis123** [comment]
I'm not sure why r - 200 doesn't give an index out of bounds exception, but somehow it works. This is the same reason why I started r at 1 - initially, peak_radius was 1, and once I increased it I did not get any errors at runtime, so I kept it.

**Comment by sriharis123** [comment]
Also, \201 is an escape character so I had to use the backslash escape character - \\\\ - for loading the data

**Comment by sriharis123** [comment]
Also to clarify I skipped 200 because those points were already checked [when checking whether r - 200 was truly the highest point] - the assumption about the data lies in that there is an evident peak within 400 data points. I'll make it a parameter of the function so that it can be less specific than only for our uses

**Comment by aboehmke** [comment]
1. I'm not sure why r - 200 doesn't give an index out of bounds exception,
but somehow it works. This is the same reason why I started r at 1 -
initially, peak_radius was 1, and once I increased it I did not get any
errors at runtime, so I kept it.
That is because you are indexing from the end of the array, e.g.
>>> y = np.array([0,1,2,3,...,99,100])
>>> y[-2]
99

2. Also, \201 is an escape character so I had to use the backslash escape
character - \ - for loading the data
hm, maybe it would be better if we used os.path.join(*path*, **paths*) (link
<https://docs.python.org/2/library/os.path.html>)

3. Also to clarify I skipped 200 because those points were already checked
[when checking whether r - 200 was truly the highest point] - the
assumption about the data lies in that there is an evident peak within 400
data points. I'll make it a parameter of the function so that it can be
less specific than only for our uses
The A and B exciton peaks are not necessarily the highest peaks. Try
starting from two input values: the wavelengths of the A and B exciton
peaks from the literature. The precision of this peak wavelength will not
be one nanometer, so search for a peak within some region around the
literature value. To go from wavelength to index, knowing that the
wavelengths array is monotonic, I found it useful to write a function, that
scans through the wavelengths and returns the index of the first instance
of wavelengths greater than the value you want to find. Alternatively, you
could use numpy.where()
<https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.where.html>,
though I'm not sure what the best condition would be to get only one index
back... I'll think about it.
Also check out numpy.amax()
<https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.amax.html#numpy.amax>
.

**Comment by aboehmke** [comment]
P.S.
3. Could use np.where(np.round(W,decimals=1) == 600.0) to find index of W
for wavelength 600 nm (W refers to your array of wavelengths)

**Pull request merged**
